// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SB.PruebaTecnica.Infrastructure.Persistence;

#nullable disable

namespace SB.PruebaTecnica.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SB.PruebaTecnica.Domain.Entities.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Departamento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("HorasTrabajadas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroSeguroSocial")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PrimerNombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("SalarioBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SalarioSemanal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SueldoPorHora")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TarifaComision")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("TipoEmpleado")
                        .HasColumnType("int");

                    b.Property<decimal?>("VentasBrutas")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Empleados", (string)null);

                    b.HasDiscriminator<int>("TipoEmpleado");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SB.PruebaTecnica.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("SB.PruebaTecnica.Domain.Entities.EmpleadoAsalariado", b =>
                {
                    b.HasBaseType("SB.PruebaTecnica.Domain.Entities.Empleado");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("SB.PruebaTecnica.Domain.Entities.EmpleadoAsalariadoPorComision", b =>
                {
                    b.HasBaseType("SB.PruebaTecnica.Domain.Entities.Empleado");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("SB.PruebaTecnica.Domain.Entities.EmpleadoPorComision", b =>
                {
                    b.HasBaseType("SB.PruebaTecnica.Domain.Entities.Empleado");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("SB.PruebaTecnica.Domain.Entities.EmpleadoPorHoras", b =>
                {
                    b.HasBaseType("SB.PruebaTecnica.Domain.Entities.Empleado");

                    b.HasDiscriminator().HasValue(2);
                });
#pragma warning restore 612, 618
        }
    }
}
